### ISSUE TITLE
Если не заполнить издательство при создании книги метод show не работает

### ISSUE THREAD

**Issue by MasalitinMaksim** [Bodigrim/reading#45]
Пример смотрите на продакшне https://reading-master.herokuapp.com/books

**Comment by Bodigrim** [comment]
Вроде пофиксил в https://github.com/Bodigrim/reading/pull/48
Хм, мне уведомление об асайменте на почту пришло, а об анасайменте - нет.

**Comment by MasalitinMaksim** [comment]
Неплохо было бы ещё в модели валидацию добавить)

**Comment by Bodigrim** [comment]
Не уверен. В принципе, может быть книга без издательства - какая-нибудь классика вроде "Илиады". И я верно понимаю, что если сделать валидацию на уровне модели, то при удалении издательства сразу пропадут все его книги?
